# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30a08e69af83d72f6b74b81cdef8bf748eb5460a6084c4e523bf477088c321e2c8718dae6650ba07380a18506604f909bcecbc71ef949f70ad3541e94b078d94

test:
  secret_key_base: 809767b2a66dd892d6b8e243f5b5e49018f630ef4c4021543792db841cdd94c611755d3866a4071bce3629cd7ff661418add7f76814b096c1cd6fe9c27b7ca93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
